config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :universities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/roster', to: 'roster#index'
  get '/', to: 'roster#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :university, optional: true
  validates :gpa, :inclusion => 0..4
end

app/models/university.rb
class University < ApplicationRecord
    has_many :students, dependent: :destroy
    validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/roster_controller.rb
class RosterController < ApplicationController
    def index
        @universities = University.all
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :gpa, :university_id)
    end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_params
      params.require(:university).permit(:name, :rank, :mascot)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roster_helper.rb
module RosterHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Rails App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/roster/index.html.erb
<html>
    <body>
        <% @universities.each do |university| %>

            <h1><%= university.name %></h1>
            <p>Rank: <%= university.rank %></p>
            <p>Mascot: <%= university.mascot %></p>
            <ul>
            <% university.students.each do |student| %>
                <li>
                    <p>
                        <%= student.name %> | GPA: <%= student.gpa %>
                        <!-- INSERT EDIT STUDENT BUTTON HERE -->
                        <%= button_to "Edit #{student.name}", edit_student_path(student.id), :method => :get %>
                    </p>

                </li>
            <% end %>
            </ul>
            <hr />
        <% end %>

        <!-- INSERT REGISTER NEW STUDENT BUTTON HERE -->
        <%= button_to "Register new student", 'students/new', :method => :get %>
    </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gpa %>
    <%= form.number_field :gpa %>
  </div>

  <div class="field">
    <%= form.label :university_id %>
    <%= form.text_field :university_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gpa</th>
      <th>University</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.gpa %></td>
        <td><%= student.university.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Gpa:</strong>
  <%= @student.gpa %>
</p>

<p>
  <strong>University:</strong>
  <%= @student.university.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/universities/_form.html.erb
<%= form_with(model: university, local: true) do |form| %>
  <% if university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.number_field :rank %>
  </div>

  <div class="field">
    <%= form.label :mascot %>
    <%= form.text_field :mascot %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Universities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rank</th>
      <th>Mascot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universities.each do |university| %>
      <tr>
        <td><%= university.name %></td>
        <td><%= university.rank %></td>
        <td><%= university.mascot %></td>
        <td><%= link_to 'Show', university %></td>
        <td><%= link_to 'Edit', edit_university_path(university) %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>New University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Back', universities_path %>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @university.name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @university.rank %>
</p>

<p>
  <strong>Mascot:</strong>
  <%= @university.mascot %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>